# Generated by Django 5.2.1 on 2025-06-07 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('fitness_class', 'client_email')},
        ),
    ]
